theme: minima
title: Chad's blog
author: Chad Powell
email: chad.powell0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A written record of my journey navaigating through the learning process of computer coding.

# social links
github_username:  Chad-Powellv1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
